import { CategoryType, Tag, CaseStudy } from './types';

export const INITIAL_TAGS: Tag[] = [
  // Industry
  { id: 't1', name: '金融', type: CategoryType.INDUSTRY },
  { id: 't2', name: '醫療', type: CategoryType.INDUSTRY },
  { id: 't3', name: '政府', type: CategoryType.INDUSTRY },
  { id: 't4', name: '零售', type: CategoryType.INDUSTRY },
  { id: 't5', name: '製造', type: CategoryType.INDUSTRY },
  // Business
  { id: 't6', name: '行銷', type: CategoryType.BUSINESS },
  { id: 't7', name: '營運流程', type: CategoryType.BUSINESS },
  { id: 't8', name: '經營管理', type: CategoryType.BUSINESS },
  { id: 't10', name: '數位通路', type: CategoryType.BUSINESS },
  { id: 't11', name: '產品創新', type: CategoryType.BUSINESS },
  { id: 't12', name: '智慧製造', type: CategoryType.BUSINESS },
  { id: 't13', name: '內容創意', type: CategoryType.BUSINESS },
  { id: 't20', name: 'IFHIR', type: CategoryType.BUSINESS },
  { id: 't21', name: '醫護團隊', type: CategoryType.BUSINESS },
  // Trends
  { id: 't14', name: 'AI應用', type: CategoryType.TREND },
  { id: 't15', name: 'APIM', type: CategoryType.TREND },
  { id: 't16', name: 'AI治理中台', type: CategoryType.TREND },
  { id: 't17', name: 'ESG', type: CategoryType.TREND },
  { id: 't18', name: '資安', type: CategoryType.TREND },
  { id: 't19', name: '主權AI', type: CategoryType.TREND },
  { id: 't22', name: '可信任AI', type: CategoryType.TREND },
  { id: 't9', name: '提升生產力', type: CategoryType.TREND },
];

export const INITIAL_CASES: CaseStudy[] = [
  {
    id: 'c1',
    title: '智慧金融風控中台',
    description: '透過 AI 治理中台即時分析交易數據，阻詐成功率提升 400%。',
    imageUrl: 'https://picsum.photos/id/48/800/600',
    solutionImageUrl: 'https://picsum.photos/id/201/800/600',
    solutionDescription: '採用分散式運算架構，結合 Graph Neural Networks (GNN) 分析複雜的資金流向圖譜。系統部署於高安全性私有雲，符合金管會資安規範，並提供即時戰情儀表板供稽核人員使用。',
    tagIds: ['t1', 't8', 't16', 't14'],
    dateAdded: Date.now()
  },
  {
    id: 'c2',
    title: '遠距醫療影像辨識系統',
    description: '協助大型醫院導入 AI 影像輔助，縮短醫生診斷時間 30%。',
    imageUrl: 'https://picsum.photos/id/24/800/600',
    solutionImageUrl: 'https://picsum.photos/id/250/800/600',
    solutionDescription: '整合 DICOM 醫療影像標準，運用 Computer Vision 模型自動標記病徵。系統具備邊緣運算能力，可在救護車或偏鄉診所離線運作，待網路連線後自動同步至醫療中心資料庫。',
    tagIds: ['t2', 't11', 't14'],
    dateAdded: Date.now() - 10000
  },
  {
    id: 'c3',
    title: '全球供應鏈 ESG 戰情室',
    description: '整合全球 50+ 工廠數據，即時監控碳排放與能源消耗。',
    imageUrl: 'https://picsum.photos/id/20/800/600',
    solutionImageUrl: 'https://picsum.photos/id/119/800/600',
    solutionDescription: '透過 IoT 感測器即時蒐集水、電、氣消耗數據，並透過 Blockchain 技術確保碳足跡數據不可篡改。自動產出符合國際標準 (GRI, SASB) 的 ESG 報告。',
    tagIds: ['t5', 't7', 't17'],
    dateAdded: Date.now() - 20000
  },
  {
    id: 'c4',
    title: '主權 AI 對話機器人',
    description: '為政府單位建置本地化 LLM 模型，確保資料不落地。',
    imageUrl: 'https://picsum.photos/id/4/800/600',
    solutionImageUrl: 'https://picsum.photos/id/60/800/600',
    solutionDescription: '基於 Llama 3 架構進行本地微調 (Fine-tuning)，餵養政府公開數據與法規資料庫。建置 RAG (Retrieval-Augmented Generation) 機制，確保回答具有法源依據，且完全在內網環境運行。',
    tagIds: ['t3', 't10', 't19', 't18'],
    dateAdded: Date.now() - 30000
  },
  {
    id: 'c5',
    title: '零售全通路行銷自動化',
    description: '運用 GenAI 生成個人化行銷文案，點擊率提升 2.5 倍。',
    imageUrl: 'https://picsum.photos/id/6/800/600',
    solutionImageUrl: 'https://picsum.photos/id/96/800/600',
    solutionDescription: '串接 CDP 客戶數據平台，分析消費者畫像。利用生成式 AI 自動針對不同客群產出 EDM、Line 推播與廣告文案。具備 A/B Test 自動優化機制。',
    tagIds: ['t4', 't6', 't14', 't13'],
    dateAdded: Date.now() - 40000
  },
  {
    id: 'c6',
    title: '智慧製造品質檢測系統',
    description: '運用 AI 視覺檢測技術，產品不良率降低 85%，檢測速度提升 10 倍。',
    imageUrl: 'https://picsum.photos/id/1015/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1018/800/600',
    solutionDescription: '整合工業相機與深度學習模型，實現即時瑕疵檢測。系統支援多種產品類型，可自動學習新產品的檢測標準。結合邊緣運算設備，確保低延遲檢測響應。',
    tagIds: ['t5', 't12', 't14', 't9'],
    dateAdded: Date.now() - 50000
  },
  {
    id: 'c7',
    title: '金融機構 API 管理平台',
    description: '建置統一 API 閘道器，整合 50+ 金融服務 API，提升開發效率 300%。',
    imageUrl: 'https://picsum.photos/id/1035/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1036/800/600',
    solutionDescription: '採用微服務架構，提供 API 版本管理、流量控制、安全認證等功能。支援 OAuth 2.0 與 API Key 雙重認證機制，並提供完整的 API 監控與分析儀表板。',
    tagIds: ['t1', 't10', 't15', 't18'],
    dateAdded: Date.now() - 60000
  },
  {
    id: 'c8',
    title: '醫療健康數據平台',
    description: '整合 FHIR 標準，建立跨院醫療數據交換平台，提升病歷調閱效率 90%。',
    imageUrl: 'https://picsum.photos/id/1037/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1038/800/600',
    solutionDescription: '基於 HL7 FHIR R4 標準建置醫療數據平台，支援結構化病歷、檢驗報告、影像資料的交換。採用區塊鏈技術確保數據完整性與不可篡改性，符合個資法與醫療法規要求。',
    tagIds: ['t2', 't20', 't21', 't18'],
    dateAdded: Date.now() - 70000
  },
  {
    id: 'c9',
    title: '可信任 AI 模型治理平台',
    description: '建立 AI 模型全生命週期管理系統，確保模型可解釋性與公平性。',
    imageUrl: 'https://picsum.photos/id/1039/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1040/800/600',
    solutionDescription: '提供模型版本控制、性能監控、偏見檢測、可解釋性分析等功能。整合 MLOps 流程，自動化模型訓練、部署與更新。支援多種 AI 框架，並提供模型公平性評估報告。',
    tagIds: ['t16', 't22', 't14', 't8'],
    dateAdded: Date.now() - 80000
  },
  {
    id: 'c10',
    title: '政府數位服務整合平台',
    description: '整合跨部門數位服務，提供一站式便民服務入口，服務滿意度提升 95%。',
    imageUrl: 'https://picsum.photos/id/1041/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1042/800/600',
    solutionDescription: '採用 API Gateway 整合各政府部門服務 API，提供統一的身份認證與授權機制。建置服務編排引擎，支援跨部門業務流程自動化。提供行動 App 與 Web 雙平台，並支援多種支付方式。',
    tagIds: ['t3', 't10', 't19', 't7'],
    dateAdded: Date.now() - 90000
  },
  {
    id: 'c11',
    title: '企業數位轉型顧問服務',
    description: '協助傳統製造業導入數位化流程，生產效率提升 60%，成本降低 25%。',
    imageUrl: 'https://picsum.photos/id/1043/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1044/800/600',
    solutionDescription: '進行數位成熟度評估，制定數位轉型路線圖。導入 IoT 感測器監控生產線，建立數據中台整合各系統數據。運用 AI 預測維護需求，減少設備故障時間。提供員工數位技能培訓計畫。',
    tagIds: ['t5', 't7', 't12', 't9'],
    dateAdded: Date.now() - 100000
  },
  {
    id: 'c12',
    title: '智慧城市交通管理系統',
    description: '整合交通數據與 AI 演算法，優化交通流量，減少壅塞時間 40%。',
    imageUrl: 'https://picsum.photos/id/1045/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1046/800/600',
    solutionDescription: '整合路口監視器、車流感測器、公車 GPS 等多源數據。運用機器學習預測交通流量，動態調整號誌時相。提供即時路況資訊給用路人，並優化公車路線規劃。支援緊急車輛優先通行功能。',
    tagIds: ['t3', 't7', 't14', 't15'],
    dateAdded: Date.now() - 110000
  },
  {
    id: 'c13',
    title: '銀行數位分行智能客服系統',
    description: '建置 AI 語音與文字雙模態客服系統，24/7 自動處理 80% 常見問題，客戶滿意度達 92%。',
    imageUrl: 'https://picsum.photos/id/1047/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1048/800/600',
    solutionDescription: '整合自然語言處理 (NLP) 與語音識別技術，支援中文、英文、台語多語言服務。採用意圖識別與實體抽取技術，精準理解客戶需求。結合知識庫與 RAG 技術，提供即時且準確的金融服務諮詢。系統具備情感分析功能，可自動轉接人工客服處理複雜問題。',
    tagIds: ['t1', 't10', 't14', 't22'],
    dateAdded: Date.now() - 120000,
    client: '大型商業銀行',
    launchDate: '2024-08-15',
    highlights: '多語言支援、情感分析、自動轉接機制',
    features: 'NLP+語音識別+知識庫整合，專案人力 15 天'
  },
  {
    id: 'c14',
    title: '醫院智能排程與資源優化系統',
    description: '運用 AI 演算法優化手術室與病床排程，設備利用率提升 35%，病患等待時間減少 50%。',
    imageUrl: 'https://picsum.photos/id/1049/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1050/800/600',
    solutionDescription: '整合 HIS 醫院資訊系統與排程資料，運用強化學習 (Reinforcement Learning) 演算法動態優化資源配置。考慮手術類型、醫師專長、設備需求、病患優先級等多重因素。提供即時排程調整建議，並支援突發狀況的應變處理。系統可預測未來一週的資源需求，提前進行規劃。',
    tagIds: ['t2', 't7', 't14', 't21'],
    dateAdded: Date.now() - 130000,
    client: '區域教學醫院',
    launchDate: '2024-09-20',
    highlights: '強化學習優化、預測性排程、突發應變',
    features: 'RL演算法+排程系統整合，專案人力 20 天'
  },
  {
    id: 'c15',
    title: '零售業庫存預測與補貨系統',
    description: '運用時間序列分析與機器學習預測商品需求，庫存週轉率提升 45%，缺貨率降低 60%。',
    imageUrl: 'https://picsum.photos/id/1051/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1052/800/600',
    solutionDescription: '整合 POS 系統、電商平台、天氣數據、促銷活動等多源數據。採用 LSTM 與 Prophet 模型預測未來 30 天商品需求。考慮季節性、趨勢性、促銷影響等因素。自動產生補貨建議，並整合供應鏈系統進行自動下單。提供庫存健康度儀表板，即時監控各商品庫存狀態。',
    tagIds: ['t4', 't7', 't14', 't9'],
    dateAdded: Date.now() - 140000,
    client: '連鎖零售集團',
    launchDate: '2024-10-05',
    highlights: '多源數據整合、自動補貨、庫存健康監控',
    features: '時間序列預測+供應鏈整合，專案人力 18 天'
  },
  {
    id: 'c16',
    title: '製造業預測性維護平台',
    description: '透過 IoT 感測器與 AI 分析，提前預測設備故障，非計劃性停機時間減少 70%。',
    imageUrl: 'https://picsum.photos/id/1053/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1054/800/600',
    solutionDescription: '部署振動、溫度、壓力等多種 IoT 感測器於關鍵設備。運用異常檢測與時間序列預測模型，提前 7-30 天預警設備故障。整合 CMMS 維護管理系統，自動產生工單並排程維修。建立設備健康評分機制，提供設備生命週期管理建議。支援邊緣運算，確保即時監控與低延遲響應。',
    tagIds: ['t5', 't12', 't14', 't9'],
    dateAdded: Date.now() - 150000,
    client: '精密機械製造廠',
    launchDate: '2024-07-12',
    highlights: 'IoT整合、預測性維護、自動工單生成',
    features: 'IoT+異常檢測+維護系統整合，專案人力 25 天'
  },
  {
    id: 'c17',
    title: '金融科技開放銀行平台',
    description: '建置符合 TSP 規範的開放銀行平台，整合 30+ 金融服務，API 調用量月增 500%。',
    imageUrl: 'https://picsum.photos/id/1055/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1056/800/600',
    solutionDescription: '遵循金管會開放銀行規範，建置 TSP (Third-Party Service Provider) 平台。提供 OAuth 2.0 與 OpenID Connect 認證機制，確保用戶授權與資料安全。整合帳戶資訊、交易資訊、商品資訊等三大類 API。建立完整的 API 監控、限流、版本管理機制。提供開發者入口網站，簡化第三方服務商整合流程。',
    tagIds: ['t1', 't10', 't15', 't18'],
    dateAdded: Date.now() - 160000,
    client: '數位銀行',
    launchDate: '2024-11-01',
    highlights: '符合法規、完整認證機制、開發者友善',
    features: '開放銀行平台+API管理，專案人力 30 天'
  },
  {
    id: 'c18',
    title: '醫療影像 AI 輔助診斷系統',
    description: '運用深度學習分析 X 光、CT、MRI 影像，協助醫師快速識別病灶，診斷準確率提升 25%。',
    imageUrl: 'https://picsum.photos/id/1057/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1058/800/600',
    solutionDescription: '基於 CNN 與 Transformer 架構訓練多模態醫學影像分析模型。支援胸部 X 光、腦部 CT、關節 MRI 等多種影像類型。提供病灶標記、嚴重程度評分、診斷建議等功能。整合 PACS 影像儲存系統，無縫嵌入醫師工作流程。系統具備可解釋性功能，標示 AI 判斷的關鍵區域，協助醫師理解 AI 決策過程。',
    tagIds: ['t2', 't11', 't14', 't22'],
    dateAdded: Date.now() - 170000,
    client: '醫學中心',
    launchDate: '2024-06-18',
    highlights: '多模態影像分析、可解釋性、工作流程整合',
    features: '深度學習模型+PACS整合，專案人力 35 天'
  },
  {
    id: 'c19',
    title: '政府智慧防災預警系統',
    description: '整合氣象、水文、地質數據，運用 AI 預測災害風險，預警準確率達 88%，疏散時間提前 2 小時。',
    imageUrl: 'https://picsum.photos/id/1059/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1060/800/600',
    solutionDescription: '整合中央氣象局、水利署、地調所等多個政府單位的即時數據。運用機器學習模型預測颱風、豪雨、土石流等災害風險。建立分級預警機制，自動發送簡訊、App 推播、廣播等多管道通知。提供災害風險地圖，協助民眾了解所在區域風險等級。整合避難所資訊系統，提供最佳疏散路線建議。',
    tagIds: ['t3', 't7', 't14', 't19'],
    dateAdded: Date.now() - 180000,
    client: '地方政府',
    launchDate: '2024-05-10',
    highlights: '多源數據整合、分級預警、多管道通知',
    features: '災害預測模型+通知系統，專案人力 28 天'
  },
  {
    id: 'c20',
    title: '零售業個人化推薦引擎',
    description: '運用協同過濾與深度學習，提供個人化商品推薦，轉換率提升 3.2 倍，平均訂單金額增加 40%。',
    imageUrl: 'https://picsum.photos/id/1061/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1062/800/600',
    solutionDescription: '整合用戶瀏覽行為、購買歷史、商品屬性、時間序列等多維度數據。採用混合推薦策略，結合協同過濾、內容推薦、深度學習模型。建立即時推薦系統，響應時間低於 100ms。支援 A/B 測試框架，持續優化推薦效果。提供推薦理由解釋，提升用戶信任度與點擊率。',
    tagIds: ['t4', 't6', 't14', 't13'],
    dateAdded: Date.now() - 190000,
    client: '電商平台',
    launchDate: '2024-09-28',
    highlights: '混合推薦策略、即時響應、A/B測試',
    features: '推薦引擎+即時系統，專案人力 22 天'
  },
  {
    id: 'c21',
    title: '製造業數位孿生 (Digital Twin) 平台',
    description: '建立生產線數位孿生模型，即時模擬與優化生產流程，產能提升 20%，能耗降低 15%。',
    imageUrl: 'https://picsum.photos/id/1063/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1064/800/600',
    solutionDescription: '整合 MES 製造執行系統、SCADA 監控系統、IoT 感測器數據，建立高保真度數位孿生模型。運用物理建模與數據驅動方法，即時反映生產線狀態。提供虛擬調試功能，在數位環境中測試新產品生產流程。建立優化引擎，自動調整生產參數以提升效率。支援 AR/VR 視覺化，協助工程師直觀理解生產流程。',
    tagIds: ['t5', 't12', 't14', 't9'],
    dateAdded: Date.now() - 200000,
    client: '電子製造大廠',
    launchDate: '2024-08-22',
    highlights: '高保真度模型、虛擬調試、AR/VR視覺化',
    features: '數位孿生平台+優化引擎，專案人力 40 天'
  },
  {
    id: 'c22',
    title: '金融業反洗錢 (AML) 智能監控系統',
    description: '運用圖神經網路分析複雜資金流向，可疑交易偵測準確率提升 50%，誤報率降低 60%。',
    imageUrl: 'https://picsum.photos/id/1065/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1066/800/600',
    solutionDescription: '整合銀行、證券、保險等多個金融機構的交易數據。運用 Graph Neural Networks (GNN) 分析資金流向圖譜，識別複雜的洗錢模式。建立規則引擎與機器學習混合模型，結合專家知識與數據驅動方法。提供可疑交易評分機制，協助合規人員優先處理高風險案件。整合法規資料庫，自動比對是否符合洗錢防制法規範。',
    tagIds: ['t1', 't8', 't14', 't18'],
    dateAdded: Date.now() - 210000,
    client: '金控公司',
    launchDate: '2024-10-15',
    highlights: '圖神經網路、混合模型、法規自動比對',
    features: 'AML監控系統+圖分析，專案人力 32 天'
  },
  {
    id: 'c23',
    title: '醫院臨床決策支援系統 (CDSS)',
    description: '整合電子病歷與臨床指南，提供即時診療建議，醫療品質指標提升 30%，用藥錯誤率降低 45%。',
    imageUrl: 'https://picsum.photos/id/1067/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1068/800/600',
    solutionDescription: '整合 HIS 醫院資訊系統、電子病歷、檢驗系統、藥局系統等多個臨床系統。建立知識庫，收錄臨床指引、藥物交互作用、過敏警示等資訊。運用自然語言處理技術，從非結構化病歷中提取關鍵資訊。提供即時臨床決策建議，包括診斷建議、用藥建議、檢查建議等。建立學習機制，持續從醫師回饋中優化建議準確度。',
    tagIds: ['t2', 't11', 't14', 't21'],
    dateAdded: Date.now() - 220000,
    client: '區域醫院',
    launchDate: '2024-07-25',
    highlights: '多系統整合、即時決策支援、持續學習',
    features: 'CDSS系統+知識庫，專案人力 38 天'
  },
  {
    id: 'c24',
    title: '零售業全通路庫存共享平台',
    description: '整合實體門市與電商倉庫庫存，實現全通路庫存共享，庫存週轉率提升 55%，缺貨率降低 70%。',
    imageUrl: 'https://picsum.photos/id/1069/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1070/800/600',
    solutionDescription: '建立統一庫存管理平台，整合實體門市 POS 系統、電商倉庫 WMS 系統、供應商系統。運用演算法動態分配庫存，根據銷售預測與地理位置優化庫存配置。支援線上訂購、門市取貨 (BOPIS) 與門市訂購、宅配到家等全通路服務模式。提供即時庫存可視化儀表板，協助管理人員掌握全通路庫存狀態。建立自動補貨機制，當某門市缺貨時自動從鄰近門市或倉庫調貨。',
    tagIds: ['t4', 't7', 't10', 't9'],
    dateAdded: Date.now() - 230000,
    client: '連鎖零售品牌',
    launchDate: '2024-11-10',
    highlights: '全通路整合、動態庫存分配、自動調貨',
    features: '庫存共享平台+全通路系統，專案人力 26 天'
  },
  {
    id: 'c25',
    title: '政府智慧停車管理系統',
    description: '整合路邊停車格與停車場數據，運用 AI 優化停車引導，平均找車位時間減少 60%，停車場利用率提升 30%。',
    imageUrl: 'https://picsum.photos/id/1071/800/600',
    solutionImageUrl: 'https://picsum.photos/id/1072/800/600',
    solutionDescription: '部署地磁感測器與影像辨識系統，即時監控路邊停車格使用狀態。整合公有與私有停車場的即時空位資訊。建立停車需求預測模型，運用歷史數據與即時交通狀況預測未來停車需求。提供智慧停車 App，引導駕駛至最近可用停車位。支援無現金支付，整合多元支付方式。建立停車大數據分析平台，協助政府規劃停車政策與設施配置。',
    tagIds: ['t3', 't7', 't14', 't10'],
    dateAdded: Date.now() - 240000,
    client: '市政府',
    launchDate: '2024-06-30',
    highlights: '即時監控、需求預測、智慧引導、無現金支付',
    features: '停車管理系統+智慧App，專案人力 24 天'
  }
];
